yaml
services:
  - type: web
    name: cloudways-bot
    env: python
    plan: free
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8485686944:AAH-NNQK2UBSraeZ9balu70-yLYZl00K_P4
